# -*- coding: utf-8 -*-
"""week 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BIbi_6XbOO1zpIh28uoVVQVHuVYl2HHb
"""

import matplotlib.pyplot as plt
x=[6,7,8,9,4,5,6,7,8,8,7]
y=[33,66,77,88,55,33,22,89,90,99,11]
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
from scipy import stats
x=[6,7,8,9,4,5,6,7,8,8,7]
y=[33,66,77,88,55,33,22,89,90,99,11]
slope,intercept,r,p,std_err=stats.linregress(x,y)
def myfunc(x):
    return slope*x+intercept
mymodel=list(map(myfunc,x))
plt.scatter(x,y)
plt.plot(x,mymodel)
plt.show()

import numpy as np
x = np.arange(1,25).reshape(12,2)
y = np.array([0,1,1,0,1,0,0,1,1,0,1,0])
x

y

pip install sci kit

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)
x_train

x_test

y_train

y_test

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=4,random_state=4)
x_train

x_train

import numpy as np
x = np.arange(1, 6).reshape(1, 5)
y = np.array([0,1,1,0,1,0,0,1,1,0,1,0])
x

import numpy as np
x = np.arange(1, 51)
x = x.reshape(2, 25)
y = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])
print(x)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=4,random_state=4,stratify=y)
x_train

x_train

y_train

x_test

y_test

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.22,shuffle=False)
x_train

x_test

y_test

x_train

y_train